### ISSUE TITLE
Add constraints in segmentation (postags, hardcoded constraints, etc.)

### ISSUE THREAD

**Issue by saberkun** [shangjingbo1226/SegPhrase#1]
Apply Part-Of-Speech tags to restrict the patterns of phrases.
Examples:
(1) Only Noun phrases
(2) RB + ADJ
(3) Verb phrases can have preposition part inside

Design: Change transition probabilities inside dynamic programming.
How to apply this constraints? (Use a [0, 1] score?)

**Comment by shangjingbo1226** [comment]
Please check out our new tool [AutoPhrase](https://github.com/shangjingbo1226/AutoPhrase), which can support English, Spanish, and Chinese.  It also consider the POS tags in segmentation!
