### ISSUE TITLE
how to allow numerals in phrases?

### ISSUE THREAD

**Issue by jeradf** [shangjingbo1226/SegPhrase#10]
By default it seems that the preprocessing removes number and symbol characters from the training text.

I would like disable that step so I can discover common phrases like _iphone_7_,  _2%_milk_,  and _6_pack_. 

Could you please point me to the string processing code that is removing number and symbol characters?

**Comment by shangjingbo1226** [comment]
There is a workaround that you can first encode all numbers as some strange English words, such as "aaaaaaaaaaaa" stands for "1".

Then, after the phrase mining, you can decode the results based on your mappings.

**Comment by Sandeep42** [comment]
>  I would like disable that step so I can discover common phrases like iphone_7, _2%milk, and 6_pack.

You can change the python code in src/frequent_phrase_mining/main.py in the line 31 from ch.isalpha() to ch.isalnum() and repeat the same thing in line 31 of src/preprocessing/compute_IDF.py as well.

Search for all mentions of isalpha and change them in C++ code as well. Compile the entire code again and I think you will be good to go.

**Comment by shangjingbo1226** [comment]
Please check out our new tool [AutoPhrase](https://github.com/shangjingbo1226/AutoPhrase), which can support English, Spanish, and Chinese. Of course, the numerical values are also supported now!
