### ISSUE TITLE
Can it run with Vietnamese corpus?

### ISSUE THREAD

**Issue by hmchuong** [shangjingbo1226/SegPhrase#11]
I have appended a short text in Vietnamese in "DBLP.5K.txt" but it went wrong with those words when I ran train_toy.sh. I don't know why it cannot read Vietnamese words, such as
 _"ngành" becomes "ng" and "nh" (2 words) in the result, all letters with signs will be disappeared

**Comment by shangjingbo1226** [comment]
We now support English, Spanish, and Chinese. Please subscribe our new method [AutoPhrase](https://github.com/shangjingbo1226/AutoPhrase) and we will let you know if we support Vietanmese.
