### ISSUE TITLE
Unable to download DBLP.txt.gz dataset

### ISSUE THREAD

**Issue by huytr4n** [shangjingbo1226/SegPhrase#15]
DBLP script can not run due to error unable to download the dataset.
http://dmserv4.cs.illinois.edu/DBLP.txt.gz

> Not Found
> 
> The requested URL /DBLP.txt.gz was not found on this server.
> 
> Apache/2.4.18 (Ubuntu) Server at dmserv4.cs.illinois.edu Port 80

**Comment by shangjingbo1226** [comment]
Fixed the url in the bash script.
