### ISSUE TITLE
Unable to download the DBLP.txt.gz dataset

### ISSUE THREAD

**Issue by Fareedah** [shangjingbo1226/SegPhrase#17]
"The requested URL /data/DBLP.txt.gz was not found on this server." Can you please update the link? Thanks.

===Downloading dataset===
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   313  100   313    0     0    591      0 --:--:-- --:--:-- --:--:--   591
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /data/DBLP.txt.gz was not found on this server.</p>
<hr>
<address>Apache/2.2.15 (Scientific Linux) Server at dmserv2.cs.illinois.edu Port 80</address>
</body></html>

**Comment by shangjingbo1226** [comment]
It should work now.
