### ISSUE TITLE
how to calculate recall in pooling evaluation？

### ISSUE THREAD

**Issue by crystal0913** [shangjingbo1226/SegPhrase#19]
Randomly sampled k Wiki-uncovered phrases from the returned candidates，and rely on human evaluators to get how many quality phrases. But i don't know the total number of quality phrases，then what's the recall mean here?

**Comment by remenberl** [comment]
We assume after merging phrases from different methods (proposed approach+baselines) we can get a relatively complete phrase pool. Recall is computed based on the ground truth collected from these merged phrases.
