### ISSUE TITLE
Couldn't find file train.sh

### ISSUE THREAD

**Issue by gomathykailas** [shangjingbo1226/SegPhrase#2]
Hi ,

I am facing an issue in SegPhrase github project.

I have cloned the SegPhrase project from github (https://github.com/shangjingbo1226/SegPhrase.git).
I couldn't find a file named "train.sh" in that project.

**Comment by remenberl** [comment]
train.sh is renamed as train_toy.sh

**Comment by gomathykailas** [comment]
Hi,

So, what is the purpose of  "_train_dplp.sh_" file ?
And can you provide details of how to get _"phrasiness metric"_ ?

I am analyzing a blog named
http://engineering.tripadvisor.com/using-nlp-to-find-interesting-collections-of-hotels/
In this blog it describes about SegPhrase algorithm under the heading "_Phrases
as raw material_" and the output we get after running it.

The output is of the form "_phrase , phrasiness metric_"
But while running the SegPhrase algorithm , i am not getting output as
desired.

So , could you please define *steps *to get the desired output as defined
in the blog

Thanks in advance,

Gomathy

**Comment by remenberl** [comment]
The train_dblp.sh will automatically download a cs bibliographic dataset
and train segphrase using that as the input source. The train_toy.sh script
is using a very tiny portion of the full dataset (stored as
data/DBLP.5K.txt) to train. After training, the phrase quality is located
at results/unified.csv. For more information about definition of phrase
quality, please refer to our paper

> - Jialu Liu_, Jingbo Shang_, Chi Wang, Xiang Ren and Jiawei Han, "_Mining
>   Quality Phrases from Massive Text Corpora
>   http://jialu.cs.illinois.edu/paper/sigmod2015-liu.pdf_”, Proc. of
>   2015 ACM SIGMOD Int. Conf. on Management of Data (SIGMOD'15), Melbourne,
>   Australia, May 2015. (\* equally contributed, slides
>   http://jialu.cs.illinois.edu/paper/sigmod2015-liu-slides.pdf)
> 
> The blog you mentioned uses a different data source from tripadvisor. If
> you would like to reproduce their results, the only way is to contact them.
> After getting their dataset, you can modify train_toy.sh by changing the
> variable RAW_TEXT to that dataset. The rest is simply running the
> train_toy.sh to generate results/unified.csv.

Best,

Jialu
