### ISSUE TITLE
ld: symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by shihui2010** [shangjingbo1226/SegPhrase#4]
Hi,
I'm using mac and I haven't dealing with any c++ environment setting before.
At first when I tried to run Make in command line, I got error: ld: library not found for -lgomp
Then, I tried installing ld and gcc4.9 by macport, and it somehow gave me new error:
ld: symbol(s) not found for architecture x86_64
How can I solved it, or I can run the code in other way?
Thanks

**Comment by remenberl** [comment]
Hi,

Our implementation natively support linux. But we have also tested MacOS
under the newest El Capitan environment. Please try the following
procedures :
1. Install the most recent XCode (7.*)
2. Install homebrew available at http://brew.sh/
3. Run "brew install gcc49" in your terminal
4. Change the g++ variable in Makefile to your gcc path
   (/usr/local/Cellar/gcc49/4.9.3/bin/g++-4.9)
