### ISSUE TITLE
cann't work with chinese corpus

### ISSUE THREAD

**Issue by wulongfeng** [shangjingbo1226/SegPhrase#5]
seems not support chinese, would you consider adding chinese support?

**Comment by shangjingbo1226** [comment]
It is coming soon but we don't have a specific date yet.

**Comment by airlsyn** [comment]
Does it support Chinese now? Thanks

**Comment by shangjingbo1226** [comment]
Please check out our new tool [AutoPhrase](https://github.com/shangjingbo1226/AutoPhrase), which can support English, Spanish, and Chinese.
