### ISSUE TITLE
"ptr exceeds the dimension", then problem finishing running segphrase on DBLP.txt (but not others)

### ISSUE THREAD

**Issue by tc64** [shangjingbo1226/SegPhrase#7]
Hi,
I notice that when running train_dblp.sh with DBLP.txt as input, I get a message "ptr exceeds the dimension" that I don't get when running DBLP.5K.txt.

In predict quality, this assertion test is failing:
predict_quality.cpp:           myAssert(ptr == dimension, "ptr exceeds the dimension");

Do you think that is the cause of the problem? Any idea why?

Thanks! screen output is below...
# Sentences = 9790215
# tokens =  103956084
# of distinct tokens =  455340
# of frequent pattern =  1940731

feature extraction done.
===Auto Label Disable===
320 labels loaded
feature dimension = 12
ptr exceeds the dimension
# Sentences = 10576779
# Unigrams = 472557

Segmentation fault
[Warning] failed to open ./results/penalty.1 under parameters = r
Segmentation fault
320 labels loaded
[Warning] failed to open results/feature_table_1.csv under parameters = r
Segmentation fault
Segmentation fault
[Warning] failed to open ./results/penalty.2 under parameters = r
Segmentation fault
===Unigram Disable===
[Warning] failed to open results/1.iter6_discard0.00//length1.csv under parameters = r
[Warning] failed to open results/1.iter6_discard0.00//length2.csv under parameters = r
[Warning] failed to open results/1.iter6_discard0.00//length3.csv under parameters = r
[Warning] failed to open results/1.iter6_discard0.00//length4.csv under parameters = r
[Warning] failed to open results/1.iter6_discard0.00//length5.csv under parameters = r
[Warning] failed to open results/1.iter6_discard0.00//length6.csv under parameters = r
Traceback (most recent call last):
  File "app_main.py", line 72, in run_toplevel
  File "src/postprocessing/filter_by_support.py", line 37, in <module>
    main(sys.argv[1:])
  File "src/postprocessing/filter_by_support.py", line 17, in main
    for line in open(segmented_corpus_filename):
IOError: [Errno 2] No such file or directory: 'results/1.iter5_discard0.00/segmented.txt'

My results directory looks like this:
-rw-rw---- 1 tcassidy tcassidy    0 Jul 28 14:32 unified.csv
-rw-rw---- 1 tcassidy tcassidy 164M Jul 28 14:29 feature_table_0.csv
-rw-rw---- 1 tcassidy tcassidy  13M Jul 28 14:11 wordIDF.txt
-rw-rw---- 1 tcassidy tcassidy  41M Jul 28 14:10 patterns.csv

**Comment by shangjingbo1226** [comment]
Maybe that's caused by the place change of the DBLP dataset. Could you try the updated bash script?

**Comment by tc64** [comment]
Thanks Jingbo, will let you know.
